### ISSUE TITLE
Works only from the end of a document, doesn't response to settings

### ISSUE THREAD

**Issue by yustnip** [AtomLinter/linter-stylint#12]
Stylint starts to work only from the end of a document (from the line 849 in my case). And I've specified in config.cson following:

```
"linter-stylint":
    colons: "never"
    sortOrder: false
```

but Styling still outputs that: "missing colon between property and value...".

**Comment by matthojo** [comment]
Have you tried running `stylint` from the cli? Do you get the same results if you do.

It should be that `linter-stylint` outputs what `stylint` reports itself, which would mean this is an issue for the https://github.com/rossPatton/stylint repo.

**Comment by yustnip** [comment]
Tried ```stylint``` from the CLI now. It works correct, options are also applied.

**Comment by matthojo** [comment]
How strange, how many error do you get in the CLI and how many does it report vie the Atom linter?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If you are still experiencing issues please feel free to re-open.
