### ISSUE TITLE
Can't get it to activate

### ISSUE THREAD

**Issue by zenopopovici** [AtomLinter/linter-stylint#13]
If I open the main file where all other stylus files are included, it works (for that file only, not for the included files).

If I open a module file (a file in a subfolder that's included in the main file), it doesn't do anything. I get "no Issues". Can't get it to work, although the terminal `stylint` works perfectly.

**Comment by steelbrain** [comment]
Well, that's a provider issue, I suggest you post this in the stylint's repo.

**Comment by zenopopovici** [comment]
How can it be a provider issue when it works from the terminal?

**Comment by steelbrain** [comment]
cc @matthojo

**Comment by matthojo** [comment]
I maybe wrong, are you opening a file which contains `@import` / `@require` statements, and you want it to lint the files to which is references?

What command are you running from the terminal?

**Comment by zenopopovici** [comment]
No, that would have been a nice to have, it wasn't working in files that were in subfolders. 
Don't know for what reason it started working now... It seems that if you don't have a .stylintrc file weird stuff happen. Sorry for the trouble and thanks for the patience.

**Comment by zenopopovici** [comment]
Really this is getting me white hairs. I've updated stylint and reinstalled the extension:

*Console*
![screen shot 2015-08-23 at 21 09 48](https://cloud.githubusercontent.com/assets/767998/9429518/5a07c3c4-49db-11e5-94aa-421c3d5f36f1.png)


*Config*
```
{
    "blocks": false,
    "brackets": "always",
    "colons": "always",
    "colors": "always",
    "commaSpace": "always",
    "commentSpace": "always",
    "cssLiteral": "never",
    "depthLimit": false,
    "duplicates": true,
    "efficient": "always",
    "extendPref": false,
    "globalDupe": false,
    "indentPref": false,
    "leadingZero": "never",
    "maxErrors": false,
    "maxWarnings": false,
    "mixed": false,
    "namingConvention": false,
    "namingConventionStrict": false,
    "none": "never",
    "noImportant": true,
    "parenSpace": false,
    "placeholders": "always",
    "prefixVarsWithDollar": "always",
    "quotePref": false,
    "semicolons": "never",
    "sortOrder": "alphabetical",
    "stackedProperties": "never",
    "trailingWhitespace": "never",
    "universal": false,
    "valid": true,
    "zeroUnits": "never",
    "zIndexNormalize": false
}

```

*Editor*
![screen shot 2015-08-23 at 21 10 48](https://cloud.githubusercontent.com/assets/767998/9429521/74f8a608-49db-11e5-829d-520536ba4266.png)

*Where stylint lives:*
![screen shot 2015-08-23 at 21 11 23](https://cloud.githubusercontent.com/assets/767998/9429522/8c9536b4-49db-11e5-8d74-41f8f46fd459.png)

*Plugin config*
![screen shot 2015-08-23 at 21 12 06](https://cloud.githubusercontent.com/assets/767998/9429527/b3b6fdd6-49db-11e5-91dc-9bc155b29bde.png)

**Comment by zenopopovici** [comment]
Seems to be related to https://github.com/AtomLinter/linter-stylint/issues/12

**Comment by matthojo** [comment]
@zenopopovici Thanks for all the information. I'll take a look into it as soon as I get a chance. My initial thinking is maybe the config file isnt getting sent to Stylint, so is falling back to the default.

**Comment by zenopopovici** [comment]
Sorry to bug you ... I've reinstalled it and played again with the settings. If I add the executable path in my config (which is the default one), the settings screen changes having 2 path fields like this:
![screen shot 2015-09-10 at 20 03 16](https://cloud.githubusercontent.com/assets/767998/9795006/011ddb5c-57f7-11e5-95f4-8077e0ea122b.png)

I still can't get it to work tough.

**Comment by alex-ketch** [comment]
I'm afraid I'm having no luck enabling it either.
Stylint works perfectly through CLI as well as SublimeLinter, can't get it to work with Atom though.

I'm using [NVM](https://github.com/creationix/nvm) if that makes a difference.
I know Linter-stylint is getting the stylint executablePath as if I change it to some random string I see an error in console of the DevTools inspector.

Updated to latest Node and NPM, using Atom 1.0.19 on Mac Yosemite 10.10.5.
Any other data I can provide to help?

**Comment by ViZhe** [comment]
@alex-ketch try https://atom.io/packages/linter-stylint-h if help wait #18 so this(linter-stylint-h) is a test package.

**Comment by alex-ketch** [comment]
@ViZhe Thanks for taking this up, managed to finally get it working.
I did run into a little issue that I managed to easily fix and [submitted a PR](https://github.com/ViZhe/linter-stylint-h/pull/1) for.

**Comment by zenopopovici** [comment]
Yep, the linter-stylint-h fixes the issue.

**Comment by lslima91** [comment]
Had the same issue. works with linter-stylint-h

**Comment by Arcanemagus** [comment]
Huh, not sure why that PR hasn't been reviewed yet, looking over it now...
