### ISSUE TITLE
Take project .stylintrc into account

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-stylint#5]
Doesn't seem to do this.

**Comment by matthojo** [comment]
This should find the projects `.stylintrc` already. It iterates backwards from the source file until it finds a `.stylintrc` file.

It will not find a `.stylintrc` file if the file is not in a directory which is a parent of the source file.

The code for this is at https://github.com/AtomLinter/linter-stylint/blob/master/lib/linter-stylint.coffee#L42-L43

**Comment by corysimmons** [comment]
I can't seem to get linter-stylint to throw warnings for *anything*. I was hoping that by adding `.stylintrc` to it that it would throw some errors (colon separation for instance), but it doesn't throw any errors. Am I doing something wrong?

**Comment by matthojo** [comment]
Do you have [Atom Linter](https://atom.io/packages/linter) installed?

If so, what are you settings? Do you have it to lint on change or just on save?

**Comment by corysimmons** [comment]
haha, yes I have it installed. It's linting on change (1000ms intervals) and save. I also have `stylint` installed via npm globally and it's in the default path for it.

**Comment by matthojo** [comment]
Very strange. If you enable `Lint Debug` in the (main) Linter package settings and open the Atom Developer Tools, do you get any errors? You should see Stylint logs as it lints.

**Comment by corysimmons** [comment]
I cleared the console and launched the project with the .styl in it and opened the console and this is what the output is.

```
Loading Emmet extensions from ~/emmet
/Users/cory/.atom/packages/emmet/lib/emmet.coffee:150 Emmet: no such extension folder: /Users/cory/emmet
/Users/cory/.atom/packages/linter/lib/utils.coffee:11 IntervalMethod: debounce
/Users/cory/.atom/packages/linter/lib/utils.coffee:11 Updating `linter` 5000 to 5000
3/Users/cory/.atom/packages/linter/lib/utils.coffee:11 IntervalMethod: debounce
/Users/cory/.atom/packages/linter-jshint/lib/init.coffee:20 activate linter-jshint
/Users/cory/.atom/packages/linter-stylint/lib/init.coffee:14 activate linter-stylint
index.js:52 Window load time: 1358ms
/Users/cory/.atom/packages/linter/lib/utils.coffee:11 command and arguments Array[4]
/Users/cory/.atom/packages/linter/lib/utils.coffee:11 is node executable: true
/Users/cory/.atom/packages/linter/lib/utils.coffee:11 beforeSpawnProcess: /Applications/Atom.app/Contents/Resources/app/apm/bin/node Array[3] Object
/Users/cory/.atom/packages/linter/lib/utils.coffee:19 stderr dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/stylint/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/stylint/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup


/Users/cory/.atom/packages/linter/lib/utils.coffee:11 stylint returned LinterStylint Array[0]
```

**Comment by corysimmons** [comment]
Of course I can't even get CLI `stylint` to throw an error no matter what nasty Stylus I put in it. The only way it throws any errors is in strict mode... Maybe the default should be strict mode for this plugin?

**Comment by matthojo** [comment]
If the CLI isn't throwing any errors with a config it might be due to your config settings? I'm not sure, it maybe worth raising it in the Stylint repo itself.

This linter package is simply a wrapper for the CLI, and pulls out the output into the correct format for Atom Linter. However the idea to have the option to put it into strict mode would be useful (#6), but having as default maybe too much for most.

**Comment by corysimmons** [comment]
Okay thanks.
