### ISSUE TITLE
Error when using reporter in .stylintrc

### ISSUE THREAD

**Issue by PalleZingmark** [AtomLinter/linter-stylint#65]
Not sure if it's feature or bug in the linter-stylint or in the [linter](https://github.com/steelbrain/linter) package, but Atom displays an error when using a custom reporter in the _.stylintrc_-file. Would be nice if the linter could just ignore such a setting, instead of displaying an error. Thoughts, ideas?

Info about using custom reporters in Stylint: 
https://www.npmjs.com/package/stylint#custom-reporters 

**Error message:**
```JavaScript
Error: module.js:341 throw err; ^

Error: Cannot find module 'stylint-stylish' 
at Function.Module._resolveFilename (module.js:339:15) 
at Function.Module._load (module.js:290:25) 
at Module.require (module.js:367:17) 
at require (internal/module.js:16:19) 
at Object.init (/Users/palle/.atom/packages/linter-stylint/node_modules/stylint/src/core/init.js:33:19) 
at /Users/palle/.atom/packages/linter-stylint/node_modules/stampit/stampit.js:91:25 
at forEach (/Users/palle/.atom/packages/linter-stylint/node_modules/mout/array/forEach.js:15:27) 
at Function.factory [as create] (/Users/palle/.atom/packages/linter-stylint/node_modules/stampit/stampit.js:89:7) 
at Object. (/Users/palle/.atom/packages/linter-stylint/node_modules/stylint/bin/stylint:42:11) 
at Module._compile (module.js:413:34) 
``` 

**.stylintrc:** (used by our building tools) 
```JSON
{
  "reporter": "stylint-stylish",
  "blocks": false,
  "brackets": "always",
  "colons": "always",
  "colors": "always",
  "commaSpace": "always",
  "commentSpace": "always",
  "cssLiteral": "never",
  "depthLimit": 3,
  "duplicates": true,
  "efficient": "always",
  "extendPref": false,
  "globalDupe": false,
  "indentPref": 2,
  "leadingZero": "never",
  "maxErrors": false,
  "maxWarnings": false,
  "mixed": true,
  "namingConvention": "BEM",
  "namingConventionStrict": true,
  "none": "never",
  "noImportant": true,
  "parenSpace": "never",
  "placeholders": "always",
  "prefixVarsWithDollar": "always",
  "quotePref": "double",
  "semicolons": "always",
  "sortOrder": false,
  "stackedProperties": "never",
  "trailingWhitespace": "never",
  "universal": false,
  "valid": true,
  "zeroUnits": "never",
  "zIndexNormalize": false
}
```

**Comment by Arcanemagus** [comment]
I actually looked into this briefly when last working on this, the problem is that the `stylint-json-reporter` is broken for current releases of `stylint` and doesn't seem to be being worked on currently (see https://github.com/sertae/stylint-json-reporter/issues/1 for the bug preventing its use). The "solution" is to write a new one... but I have no interest in maintaining that myself 😛.

**Comment by PalleZingmark** [comment]
I'm using the [stylint-stylish](https://github.com/SimenB/stylint-stylish) reporter, but I guess that reporter is also broken, or is it how they are currently implemented?

**Comment by Arcanemagus** [comment]
I'm not sure, checking.

**Comment by Arcanemagus** [comment]
Actually, it looks like `stylint-stylish` supports columns in it's output. So we could force output in that format inside this package and parse that instead of the default `stylint` output which may or may not be using a different reporter.

I was hoping to use the JSON reporter as that can just be directly parsed, oh well.

**Comment by Arcanemagus** [comment]
Hmmm, the `stylint-stylish` reporter doesn't have any _text_ on the line showing the error type, just the color.

**Comment by Arcanemagus** [comment]
Okay, after some further digging, you can get it to output the color by specifying the `"verbose": true` option, but there is no way to get the rule name using that reporter.

**Comment by Arcanemagus** [comment]
This is waiting on a release of `stylint-json-reporter` incorporating the changes from https://github.com/sertae/stylint-json-reporter/pull/2.

**Comment by Arcanemagus** [comment]
v0.3.1 of `stylint-json-reporter` has been published, finishing up the branch I started with that now!
