### ISSUE TITLE
Error with stylint

### ISSUE THREAD

**Issue by markoradak** [AtomLinter/linter-stylint#92]
<img width="926" alt="screen shot 2018-04-02 at 1 35 27 pm" src="https://user-images.githubusercontent.com/9327301/38195321-45896c90-367d-11e8-9657-7cec6297913a.png">

Getting this error thrown in the console upon save. 
Tried updating stylint version to 1.5.9, but the error persists.

**Comment by Arcanemagus** [comment]
It looks like that's an error coming from the `stylint` code while it is trying to parse your configuration file. I would make sure that it is valid JSON, but as the error is coming from the `stylint` code there isn't anything that can be done here about this bug.
